version: 2
updates:
  # Root package (library / core module)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "UTC"
    groups:
      major-only:
        patterns:
          - "*"
        update-types:
          - "major"

  # Sample Expo app
  - package-ecosystem: "npm"
    directory: "/sample-expo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:10"
      timezone: "UTC"
    groups:
      major-only:
        patterns:
          - "*"
        update-types:
          - "major"

  # Sample pure React Native app
  - package-ecosystem: "npm"
    directory: "/sample-react-native"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:20"
      timezone: "UTC"
    groups:
      major-only:
        patterns:
          - "*"
        update-types:
          - "major"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:40"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
