name: Setup
description: Setup Node.js, Yarn, and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: |
        # Try Yarn v1 first, then Yarn Berry setting, fallback to default location
        DIR=$(yarn cache dir 2>/dev/null || yarn config get cacheFolder 2>/dev/null || echo "$HOME/.cache/yarn")
        echo "dir=$DIR" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
          .yarn/cache
          .yarn/unplugged
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
